# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

definitions:
  workspace: &workspace
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/ysugimoto/cascade-config
    docker:
      # specify the version
      - image: circleci/golang:1.12.0
    environment:
      - PORT=3333
      - HOST=env.localhost
      - TOKEN=token_from_env

  job_presets: &job_presets
    build:
      <<: *workspace
      steps:
        - checkout
        - run: GO111MODULE=on go test

jobs:
  <<: *job_presets

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
